### ISSUE TITLE
train on other embeddings

### ISSUE THREAD

**Issue by Monduiz** [ccsasuke/umwe#3]
Could this be used to map words to another embeddings than fasttext, something like paragram embeddings? Would anything have to change?

**Comment by ccsasuke** [comment]
In principle nothing would have to change, as long as the other embeddings can be read by the code (embeddings are in the same txt format as fasttext).
Alternatively, if the embeddings are in a different format, and you don't want to convert it to the fasttext format, then you may want to modify the code for reading the embeddings (utils.load_embeddings).
