### ISSUE TITLE
assertion error assert os.path.isfile(params.tgt_emb)

### ISSUE THREAD

**Issue by Monduiz** [ccsasuke/umwe#4]
I am getting this error: 

`File "unsupervised.py", line 110, in assert os.path.isfile(params.tgt_emb)                                        AssertionError`

I have placed embeddings in a directory and I am using this command:

`python unsupervised.py --src_embs /data_disk/embeddings/crawl-300d-2M-subword.vec --src_langs en --tgt_lang fr --exp_path  /data_disk/umwe/data`

I tried --emb_dir but its not part of the options.

**Comment by ccsasuke** [comment]
Did you specify the path to the target language embeddings via --tgt_emb ?

**Comment by Monduiz** [comment]
I think I am misunderstanding the instructions. What should --tgt_emb be if I am using a source embeddings in English (glove or fasttext crawl) and I want to obtain French mapping to that space?

**Comment by ccsasuke** [comment]
It should the path to a monolingually trained French embedding using the same algorithm as English (GloVe or FastText).

**Comment by Monduiz** [comment]
I was hoping to use this to get a shared space for french with the Glove pretrained. I am going to close this as I need to test more and go back to the papers.
