### ISSUE TITLE
RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.

### ISSUE THREAD

**Issue by learnercat** [ccsasuke/umwe#5]
Hi! I am learning about UMWE paper and trying to re-producing results from this model.
I got errors as below:

`.......................`  
`INFO - 02/27/19 10:02:36 - 0:34:57 - 1500 source words - csls_knn_10 - Precision at k = 10: 83.533333`
`INFO - 02/27/19 10:02:36 - 0:34:57 - word translation precision@1: 68.61333`
`INFO - 02/27/19 10:03:09 - 0:35:30 - Loaded europarl de-en (773704 sentences).`
`Traceback (most recent call last):`
`File "unsupervised.py", line 161, in <module>`
` evaluator.all_eval(to_log)`
`File "/multi_embedd/umwe/src/evaluation/evaluator.py", line 335, in all_eval`
`self.sent_translation(to_log)`
`File "/multi_embedd/umwe/src/evaluation/evaluator.py", line 228, in sent_translation`
`method=method, idf=idf`
`File "/multi_embedd/umwe/src/evaluation/sent_translation.py", line 74, in get_sent_translation_accuracy`
`emb2 = emb2.cpu().numpy()`
`RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.`

Could anyone give me advice or comment?
Thanks.

**Comment by ccsasuke** [comment]
Hmm it might be some legacy code that didn't get updated when I migrated to PyTorch 0.4 and up. 
Could you try simply following the suggestion and change it to `emb2 = emb2.cpu().detach().numpy()` ?

Let me know if that doesn't fix this error and I can investigate further.

**Comment by learnercat** [comment]
Yes, I trained it successfully. 
I changed line 73-74 as below
` # get word vectors dictionaries`
` #emb1 = emb1.cpu().numpy()`
` #emb2 = emb2.cpu().numpy()`
` emb1 = emb1.cpu().detach().numpy()`
` emb2 = emb2.cpu().detach().numpy()`
Thank you very much!

**Comment by jaggernaut007** [comment]
This happens when I use it on flask, else, nothing!

**Comment by parasmemon** [comment]
167         probs = self.softmax(Y)
    168         # For each sample pick highest probability and translate that to class labels
--> 169         classes = self.classes[torch.argmax(probs, axis=1).cpu().detach().numpy()].reshape(-1, 1)
    170         return classes, probs.detach().cpu().numpy()
    171 

RuntimeError: Can't call numpy() on Variable that requires grad. Use var.detach().numpy() instead.



I am getting same error. Need help

**Comment by ccsasuke** [comment]
@parasmemon Hmm this looks strange as the code shown above is already doing "detach().numpy()". Can you post the full stack trace?

Also, which file is the code you attached located in?

**Comment by parasmemon** [comment]
def use(self, X):
        # Set input matrix to torch.tensors
        X = torch.from_numpy(X).float().to(self.device)
        # Standardize X
        X = (X - self.Xmeans) / self.Xstds
        # Calculate output of net for all samples in X
        Y = self.forward(X)
        # Convert output to class probabilities
        probs = self.softmax(Y)
        # For each sample pick highest probability and translate that to class labels
        classes = self.classes[torch.argmax(probs, axis=1).cpu().detach().numpy()].reshape(-1, 1)
        return classes, probs.detach().cpu().numpy()

This is the function save in one file name "nn_torch"

Importing "nn_torch" file:

import cnn_torch as nn

def percent_correct(Y, T):
    return 100 * np.mean(Y == T)

def CNN_nnet(xTrain_CN, yTrain_CN, xTest_CN, yTest_CN):
    nnet = nn.CNN1D(n_channels=42, n_inputs=6251, # channel and no. of inputs changes based on the dimension of data
                    n_hiddens_per_conv_layer=[2], 
                    patch_size_per_conv_layer=[50], stride_per_conv_layer=[1],                
                    n_hiddens_per_fc_layer=[100], n_outputs=2,
                    activation_function='softmax', device='cpu')
    # nnet.train(xTrain_CN, yTrain_CN, batch_size=600, n_epochs=200, learning_rate=0.001, method='sgd')
    nnet.train(xTrain_CN, yTrain_CN, batch_size=50, n_epochs=1, learning_rate=0.001, method='scg')
    plt.plot(nnet.error_trace, '*')
    Ytrain_balanced, _ = nnet.use(xTrain_CN)
    Ytest, _ = nnet.use(xTest_CN)
    print(f'% Correct:  Train {percent_correct(Ytrain_balanced, yTrain_CN):.2f}, Test {percent_correct(Ytest, yTest_CN):.2f}')

CNN_nnet(x_train16, y_train16, x_test16, y_test16)

**Comment by ccsasuke** [comment]
@parasmemon Just to clarify, are you sure this is the correct repo to post your question? The code you attached doesn't seem to be from this repo.

**Comment by parasmemon** [comment]
@ccsasuke This is my own code. I am trying to search for solution. I found the detach().numpy() command here.
Sorry I posted on wrong repo. If you understand the solution, pls help me.

**Comment by ccsasuke** [comment]
@parasmemon I see. Unfortunate I don't know the solution for your case either. The original error in this issue was fixed by adding ".detach()" before ".numpy()", but your code already has ".detach()" to start with.

Have you checked what torch.argmax() returns? I remember it returns a tuple or something.
