### ISSUE TITLE
Not using multiple GPUs

### ISSUE THREAD

**Issue by hammad26** [ccsasuke/umwe#6]
Hi
I have 2 GPUs available. When running this code it is using only one GPU and other is in ideal state. I am getting warning about memory on GPU1. Is this code capable of using multiple GPUs?

WARN: increase temp memory to avoid cudaMalloc, or decrease query/add size

Thanks

**Comment by ccsasuke** [comment]
Unfortunately multi-GPU training is not supported at this time.
