### ISSUE TITLE
Impossible to import Faiss-GPU

### ISSUE THREAD

**Issue by GabrielLin** [ccsasuke/umwe#7]
I use `conda install faiss-gpu -c pytorch` to install faiss-gpu. My version is 1.4.0 and I encountered the above warning when running training scripts. But I can see that my python process was using GPU. Could you give me some suggestions?

What is your training time using GPU and CPU?

Thanks.

**Comment by ccsasuke** [comment]
Sorry but I don't know much about the installation of the Faiss library. Perhaps https://github.com/facebookresearch/faiss is a better place to seek for help on this.

Training on GPU depends on the number of languages, number of epochs, etc. With the default parameters, it takes about 4-5 hours to train a multilingual embedding over 4-6 languages if I remember correctly. I haven't done training on CPU.
