### ISSUE TITLE
MULTILINGUAL PSEUDO-SUPERVISED REFINEMENT : AssertionError

### ISSUE THREAD

**Issue by saharghannay** [ccsasuke/umwe#8]
Hi, I got this error when training a multilingual embeddings using this command line :
python unsupervised.py" --exp_path $res_dir --dis_most_frequent 0  --n_epochs 30   --device cuda --export txt --src_langs fr de --tgt_lang en --emb_dim 100 --max_vocab -1 --src_embs $fr_em $de_em --tgt_emb $de_em 

Do you have an idea please how can I solve this problem. 
Thank you

- ----> MULTILINGUAL PSEUDO-SUPERVISED REFINEMENT <----
                                     
                                     
INFO - 04/06/20 18:00:10 - 0:15:59 - * Reloading the best fr to en model from /debug/19k7t4cexy/best_mapping_fr2en.t7 ...
INFO - 04/06/20 18:00:10 - 0:15:59 - * Reloading the best de to en model from /debug/19k7t4cexy/best_mapping_de2en.t7 ...
INFO - 04/06/20 18:00:10 - 0:15:59 - Starting refinement iteration 0...
INFO - 04/06/20 18:00:10 - 0:15:59 - Building the train dictionary ...
Traceback (most recent call last):
  File "/tools/git/umwe/unsupervised.py", line 190, in <module>
    trainer.build_dictionary()
  File "/tools/git/umwe/src/trainer.py", line 229, in build_dictionary
    self.dicos[(lang1, lang2)] = build_dictionary(src_emb, tgt_emb, self.params)
  File "/tools/git/umwe/src/dico_builder.py", line 157, in build_dictionary
    s2t_candidates = get_candidates(src_emb, tgt_emb, params)
  File "/tools/git/umwe/src/dico_builder.py", line 109, in get_candidates
    assert all_scores.size() == all_pairs.size() == (n_src, 2)
AssertionError

**Comment by ccsasuke** [comment]
Hi, I haven't seen this error before, and it's challenging to debug by just looking at this static log.
Have you tried setting a smaller "max_vocab" (For example, --max_vocab 1000)?

**Comment by saharghannay** [comment]
Hi,
Ok i will try,
But is it necessary to activate the REFINEMENT option ? 

Thank you

**Comment by ccsasuke** [comment]
Although it is not "necessary", turning REFINEMENT on will significantly improve the model accuracy.

**Comment by saharghannay** [comment]
Hi I tried with --max_vocab 1000 but I still have the same assertion error :
assert all_scores.size() == all_pairs.size() == (n_src, 2)

I checked the sizes of those difference tensors and I found that all_scores.size()= 14833,  all_pairs.size()=14833, and n_src=15000.

**Comment by ccsasuke** [comment]
Just a random guess, can you try lowering `--dico_max_rank` to be smaller than 14833?
```
parser.add_argument("--dico_max_rank", type=int, default=15000, help="Maximum dictionary words rank (0 to disable)")
```

**Comment by saharghannay** [comment]
Should we use the same vocabulary size for all languages, because the for my case they have difference sizes ; 17721 for "fr", "2799" for en and "15838" for de. 
In my case "en" is the target language. 

thanks

**Comment by ccsasuke** [comment]
I actually haven't tried using such a small vocabulary. (My vocab size was 200k for each language.) There might be some bugs related to vocab cutoff (such as the argument I mentioned earlier --dico_max_rank), but I don't have any experience on this specific issue. I don't think the size of the vocabularies need to be exactly the same though.

**Comment by saharghannay** [comment]
Hi,
Ok thank you, for your answer. 

Best
Sahar

**Comment by ccsasuke** [comment]
Closed due to inactivity.
